### ISSUE TITLE
Some Bug on this demo

### ISSUE THREAD

**Issue by sleepingPhD** [TUHH-ICS/2023-code-IFAC-A-Safe-Bayesian-Optimization-Algorithm-for-Tuning-at-EuXFEL#1]
I tried this code on Win11+Matlab R2022a+GPML V4.2. When I run th file "testAlgorithm.m",it just shows error:

Unrecognized field name "MaxFunEvals".

Error in fitGP (line 43)
                    [hyp_new{i}, funval]=minimize(hyp, @gp, -opts.MaxFunEvals, inf_, mean_, cov_, lik_, x, y);

Error in bayesOptima (line 171)
        [hyp,~,~]=fitGP(hyp,inf_,mean_,cov_,lik_,xt(1:counter,:),yt(1:counter,:),opts,algo_data);

Error in lineBO (line 100)
    [xopt,yt_new, xt, yt] = bayesOptima(hyp,inf_,mean_,cov_,lik_,acq_func,obj_func,cond,opts_BO,xopt,algoStruct);

Error in testAlgorithm (line 231)
    [xopt,X,Y,DIM]=lineBO(hyp,inf_,mean_,cov_,lik_,acq, fun,cond,opts,opts_lBO,x0);

what's the problem?
Thank you

**Comment by jaa-cmd** [comment]
There is a typo in line 41 in "fitGP.m". Replace oldOpts.maxFunEvals => oldOpts.**M**axFunEvals. In addition, in "testAlgorithm.m", line 196 should be replaced by "opts.minFunc.MaxFunEvals = -50;".

**Comment by jaluebsen** [comment]
Hi, 
there is a typo in line 41, replace it by "oldOpts.MaxFunEvals = 200; ". In addition, in "testAlgorithm.m" replace line 196 with "opts.minFunc.MaxFunEvals = 50;".
I corrected these errors with the last commit. 
Thank you for pointing this out!
